# from:
# https://community.home-assistant.io/t/tuya-wifi-smart-socket-cb2s-esphome-configuration/719413
# flashing:
# https://docs.libretiny.eu/docs/platform/beken-72xx/#flashing

esphome:
  name: socket-x  # I just number the sockets in incrementing order
  friendly_name: "Socket X"
  # platformio_options:
  #   lib_ignore:
  #     - RPAsyncTCP

# Pinout for reference: https://docs.libretiny.eu/boards/cb2s/#pinout
bk72xx:
  board: cb2s
  framework:
    version: latest
    loglevel: debug
    debug:
      - wifi
      - ota
    sdk_silent: auto
    uart_port: 2
    gpio_recover: false
    options:
      LT_LOG_HEAP: 1
      LT_AUTO_DOWNLOAD_REBOOT: 1

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""   

# packages:
#   wifi: !include wifi.yaml

# ota:
#   - platform: esphome
#     password: ""   # OTA passwords are important, use one.

wifi:
  ssid: LINJIA
  password: 050208linjia

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Socket X Fallback Hotspot"
    password: "deadbeef"   # Set something sensible of course

# If you want it, can leave the captive portal config here
captive_portal:
web_server:

substitutions:
  bl0937_voltage_divider: "750"
  bl0937_current_resistor: "0.0025 ohm"

# The main relay is connected to P26
switch:
  - platform: gpio
    name: Socket
    pin: P26
    id: socket1
    on_turn_on:
      then:
        light.turn_on: led1
    on_turn_off: 
      then:
        light.turn_off: led1

# The button on the side of the socket is wired to P11
binary_sensor:
  - platform: gpio
    pin:
      number: P11
      mode:
        input: true
        pullup: true
      inverted: true
    name: Button
    on_click:
      min_length: 50ms
      then:
        switch.toggle: socket1

# The LED is directly controlled via the state of the relay with the switch above
light:
  - platform: binary
    name: "LED"
    id: led1
    output: light_output
    internal: true

output:
  - id: light_output
    platform: gpio
    inverted: true
    pin: P8

# The pins were checked with a multimeter and the datasheet for the built in BL0937.
sensor:
  - platform: uptime
    name: Uptime
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: hlw8012
    model: BL0937
    cf_pin:
      number: P7
      inverted: true
    cf1_pin:
      number: P6
      inverted: true
    sel_pin:
      number: P24
      inverted: true
    current:
      name: BL0937 Current
    voltage:
      name: BL0937 Voltage
    power:
      name: BL0937 Power
    energy:
      name: BL0937 Energy
    voltage_divider: $bl0937_voltage_divider
    current_resistor: $bl0937_current_resistor
    update_interval: 10s

